<a href="https://colab.research.google.com/github/brendenwest/ad450/blob/master/2_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy & Pandas
___

## Reading

- McKinney, Chapters 4 - 5
- https://blog.growingdata.com.au/a-guided-introduction-to-exploratory-data-analysis-eda-using-python/

## Practice
- https://www.datacamp.com/community/tutorials/python-numpy-tutorial
- https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python
- https://nbviewer.org/github/pydata/pydata-book/blob/2nd-edition/ch04.ipynb
- https://nbviewer.org/github/pydata/pydata-book/blob/2nd-edition/ch05.ipynb 

## Learning Outcomes

- NumPy multi-dimensional array objects
- Array arithmetic and indexing
- Vectorized array operations
- Conditional logic as array operations
- Group-wise data manipulation
- Pandas data structures - Series and DataFrame
- Data selecting & filtering
- Computing descriptive statistics


# NumPy

---

NumPy is a foundational package for numerical computing in Python.

*   NumPy provides `ndarray`, an efficient multi-dimensional array supporting fast array-oriented arithmetic operations.
*   Can perform math operations on entire arrays without using for loops
*   Can perform common array operations like sorting, unique, & set 
*   Linear Algebra, random number generation and Fourier transform capabilities
*   C api for connecting with C, C++, & FORTRAN libraries
*   Can map data directly onto underlying disk or memory representation


### Efficiency
- NumPy stores data in contiguous memory blocks
- NumPy stores data with single type so operations don’t require type checking
- Performs complex computations on entire arrays without the need for loops
- Operations don’t copy arrays by default

NumPy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory.

NumPy is designed & optimized for **vectorized** (batch) operations on array data without `for` loops

- Arithmetic operations between equal-size arrays apply the operation element-wise - multiplication, addition, subtraction, division
- Scalar operations propagate the scalar argument to each element in the array
- Comparisons between equal size arrays yield boolean arrays


### Creating arrays
NumPy provides the `ndarray` a multi-dimensional array structure optimized for fast numeric operatons.

ndarrays are constructed from sequences of homogenous values.

Unless explicitly specified, `np.array` infers a data type for the created array and stores the data type in a special `dtype` metadata object.


In [3]:
import numpy as np

In [5]:
# create an array from literal values
numbers = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(numbers) 

print("\nInspect the array\n--------------")
print("dimensions:",numbers.ndim)  # ndarrays have dimensions
print("shape:\t",numbers.shape)    # ndarrays have shape (numer of rows & columns)
print("size:\t",numbers.size)     # number of elements in the array
print("datatype",numbers.dtype)    # numpy determines the datatype
print("bytes:\t", numbers.nbytes)  # total bytes consumed by the array

[[1 2 3 4]
 [5 6 7 8]]

Inspect the array
--------------
dimensions: 2
shape:	 (2, 4)
size:	 8
datatype int64
bytes:	 64



`ndarray` has built-in methods to create special arrays.

In [6]:
# Create an array of ones
ones = np.ones((3,4))
print(ones, "\n")

# Create an array of zeros
zeros = np.zeros((3,4), dtype=np.int16)
print(zeros, "\n")

# Create an array with random values
rando = np.random.random((2,2))
print(rando, "\n")

# Create an empty array
empty = np.empty((3,2))
print(empty, "\n")

# Create a full array
full = np.full((2,2),7)
print(full, "\n")

# Create an array of evenly-spaced values. last value is increment.
even = np.arange(10,25,5)
print(even, "\n")

# Create an array of evenly-spaced values. last param is # of values.
line = np.linspace(0,2,9)
print(line, "\n")


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[[0.43096668 0.09210349]
 [0.87507884 0.745515  ]] 

[[4.64551696e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]] 

[[7 7]
 [7 7]] 

[10 15 20] 

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ] 



### Indexing & Slicing

NumPy supports data access with Python-like indexing & slicing

- One-dimensional ndarrays act similar to Python lists
- `ndarray` dimensions are sometimes referred to as axes - e.g. in a 2d array axis 0 is the ‘rows’ and axis 1 is the ‘columns’
- ndarray slices are **views** on the original array and not copied. Any changes to the view are reflected in the source array


In [10]:
arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr1d[5:8]  # select data based on index position


array([6, 7, 8])

In [8]:
# Scalar values can be propagated (aka broadcast) to each element in a slice
arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr1d[5:8] = 12
arr1d

array([ 1,  2,  3,  4,  5, 12, 12, 12])

In [11]:
# array subsets must be copied explicitly
new_array = arr1d[5:8].copy()
new_array

array([6, 7, 8])

In [12]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# either syntax can be used to select elements in mult-dimensional arrays:

arr2d[0][2]
arr2d[0, 2]

# in mult-dimensional arrays, slicing that omits later indices will return a lower-dimensional ndarray

# Subarrays can be accessed with slices:

arr2d[:2, 1:] # select first two rows and all but first column
arr2d[:2, 2]  # select first two rows and only 3rd column


array([3, 7])

In [14]:
# slicing a mult-dimensional array with just one index will return a lower-dimensional ndarray
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2d[1]

array([5, 6, 7, 8])

### Boolean Indexing

NumPy supports boolean expressions in place of indices, where the expression results in an array of boolean values with the same length as the axis it’s indexing

In [23]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randint(2, size=(7, 4)) # create an array of random values
data[names == 'Bob'] # returns rows from ‘data’ whose index matches 'True' values in boolean array va

array([[1, 0, 1, 0],
       [0, 0, 1, 0]])

- The expression can be assigned to a variable and used in place of slicing

In [18]:
cond = names == 'Bob'
data[cond]

array([[-0.77834192,  0.02334717,  0.48992906,  1.31482435],
       [-0.28102981,  0.63581827,  1.05070863, -1.34694174]])

- The expression can be negated

In [24]:
cond = names == 'Bob'
data[~cond]

array([[0, 0, 0, 0],
       [0, 0, 1, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 0]])

- The expression can be combined with other indices

In [25]:
cond = names == 'Bob'
data[cond, 2:]

array([[1, 0],
       [1, 0]])

- boolean expressions can be combined with logical operators

In [26]:
cond = (names == 'Bob') | (names == 'Will')
data[cond]

array([[1, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 0],
       [1, 1, 1, 0]])

### Array Oriented Programming

NumPy supports **vectorization** where data processing is executed as array expressions without **for loops**. Vectorized operations can be 1-2 orders of magnitude faster that pure Python equivalents.

Any arithmetic operation between equal-size arrays applies the operation element-wise.


In [15]:
array1 = np.array([[1., 2., 3.], [4., 5., 6.]])

print(array1)

# element-wise addition
print()
print(array1 + array1)

# element-wise multiplication
print()
print(array1 * array1)

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]]

[[ 1.  4.  9.]
 [16. 25. 36.]]


Comparisons between arrays of the same size yield boolean arrays:

In [16]:
array2 = np.array([[0., 4., 1.], [7., 2., 12.]])

array2 > array1

array([[False,  True, False],
       [ True, False,  True]])

### Universal Functions

NumPy provides universal functions the can perform element-wise operations on array data. They are fast vectorized wrappers for simple functions that take a scalar value and produce one or more scalar results.

- Unary functions - e.g. sqrt, exp - perform element-wise transformations
- Binary functions - e.g. add, maximum - take two arrays and return a single-array as the result
- Ufuncs can use an optional ‘out’ parameter to perform in-place transformations


### Conditional Logic

- np.where() is a vectorized ternary expression. For example, to take a value from `arr1` whenever the corresponding value in `cond` is True, and otherwise take the value from `arr2`:


In [31]:
arr1 = np.ones(5)
arr2 = np.zeros(5)
cond = np.array([True, False, True, True, False])

# 2nd & 3rd parameters can be arrays or scalars
result = np.where(cond, arr1, arr2)
result

array([1., 0., 1., 1., 0.])

### Math & Statistical Methods

NumPy can compute statistics for an entire array or the data along a single axis.
- Can compute aggregations by invoking the array instance method or the top-level NumPy function
- Can specify whether to compute across rows or columns
- Can use `sum` to count number of True values in a boolean array 

Methods:
- mean
- sum
- cumsum 

In [44]:
arr = np.random.randint(4, size=(5, 4))

# calculate for all values in the array
arr.mean()
arr.sum()

27

In [35]:
# calculate across a single axis
arr.mean(axis=1)
arr.sum(axis=0)

array([ 6,  7,  5, 11])

In [45]:
arr.cumsum()
arr.cumsum(axis=0)
arr.cumprod(axis=1)

array([[ 0,  0,  0,  0],
       [ 2,  4,  8, 16],
       [ 1,  0,  0,  0],
       [ 2,  6, 12, 12],
       [ 1,  0,  0,  0]])

# Pandas
___

pandas supports data structures and data manipulation tools designed for fast & easy data cleaning and analysis.

pandas adopts array-based computing from NumPy, but is designed for tabular or heterogenous data.

pandas has two primary data structures:

- **Series** - one-dimensional array-like object with a sequence of values having the same datatype
- **DataFrame** - rectangular table of data with ordered collection of columns, each of which can be a different value type

### Series

Has a sequence of values and an associated array of data labels called its index. Sort of like an ordered dict with mapping of index values to data values.

- If not specified otherwise, the index values are sequential integers
- Index values can be strings
- Index-value link is preserved when the Series is filtered or modified
- Series data can be selected by indexing on label 
- Both the Series and the index have a name attribute

A Series can be created directly from a python dict. By default, data will be stored in sorted order of the keys, but you can specify a different order.

pandas can automatically determine datatype of values when a Series is created, but datatype can also be specified.

A Series index can be altered in-place by assigning new values.


### DataFrame

A pandas DataFrame is sort of a dict of Series all sharing the same index.

- DataFrames have both row and column indices
- DataFrames are physically 2D, but can represent higher-dimensional data using hierarchical indexing
- DataFrame rows are sometimes referred to as axis=0
- DataFrame columns are sometimes referred to as axis=1

By default, DataFrame columns are created in sorted order of keys. Order can also be specified.

A column can be retrieved as a Series by bracket or dot notation:
```
frame[‘column’]
frame.column
```
The returned Series will have the same index as the DataFrame and with the name attribute appropriately set.

Column data can be assigned new values, either a scalar or array-like values. Lists or arrays assigned to a column must have the same length as the column. 

A Series can be assigned to a column, with its index aligning to the DataFrame’s index.

Syntax for creating a new column is similar to assignment, but only bracket notation works.

Columns can be removed with the **del** method.

DataFrames can be populated from a variety of array-like structures.

Missing values in the sort data will be populated with `null` or `NaN` depending on column data type.


#### Indexes & Slicing

Index objects 
- are immutable and hold axis labels & metadata 
- behave like sets, but can contain duplicate labels
- Can be accessed like so:
```
	frame.index	# returns rows index
	frame.columns	# returns columns index
```
- Support a number of set methods and properties

DataFrames can be reindexed to rearrange data according to a new index, as long as labels are unique.

Reindex can introduce missing values or fill in missing values explicitly.

Reindex can alter row index, columns, or both.

Entries can be dropped from an axis using index labels. For DataFrames, drop will automatically drop rows unless columns axis is specified.

Methods like drop, which modify the size or shape of a Series or DataFrame, return a new object unless you specify inplace=True

Index labels can be used for data selection or filtering.

Series data can be indexed by label or data value. In either case, this can be a single value or a sequence.

Slicing a Series with labels differs from normal Python - the endpoint is inclusive.

DataFrames indexing returns one or more columns using column names.

DataFrames support row selection with slicing similar to Python, as a convenience, but can also be done with a boolean array.

DataFrame rows can also be selected by axis labels (loc) or integers (iloc). 

Each method takes two parameters - row select and column selection. Parameter values can be scalar, a sequence, or a slice.

DataFrames also support selecting a single value at a row & column position.


#### Arithmetic & Data Alignment

When pandas objects are added, the resulting index is a union of the source indexes. Where index labels don’t overlap, missing values are inserted.

By default, arithmetic between DataFrame and Series matches the index of the Series on the DataFrame’s columns, broadcasting down the rows.

  `frame - series`

To broadcast over columns instead, matching on the rows, you have to use arithmetic method and specify the axis to match on:

  `frame.sub(series, axis='index')`

NumPy ufuncs can be applied to pandas objects.

Pandas can also **apply()** an array function to each column or row of a DataFrame. The applied function can return a scalar or a Series.

By default, apply() is invoked per column, but you can specify `axis=’columns’` instead to invoke for each row.

Element-wise functions can be applied with **applymap()**. 


#### Sorting & Ranking

pandas objects can be sorted by index label using **sort_index()** in ascending or descending order.

DataFrames can be sorted by either axis.

**sort_values()** has similar syntax, but sorts the object by values instead. Data in one or more columns can be used as sort keys when sorting a DataFrame.

**rank()** returns the rank of data points in an array. By default, rank() breaks ties by assigning each item the group mean rank. Rank can also be assigned according the order values are observed in the data.

For DataFrames, rank can be computed over the rows or columns.


#### Computing Descriptive Statistics

pandas objects support common math & statistical methods, mostly for **reductions** or summary statistics - methods that extract a single value from a Series or a Series of values from the rows or columns of a DataFrame.

NA values are excluded by default.

**idxmin()** and **idxmax()** return the index value where minimum or maximum values are found.

**describe()** returns multiple summary statistics in one  pass.
